name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.11']

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install

    - name: Run Black
      run: poetry run black alieninvasion --check

    - name: Run MyPy
      run: poetry run mypy alieninvasion

    - name: Run Flake8
      run: poetry run flake8 alieninvasion

#    - name: Run Pytest
#      run: poetry run pytest